name: Test Suite

# Run against all commits and pull requests.
on: [ push, pull_request ]

jobs:
  test_matrix:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
        gemfile:
          - gemfiles/faraday-0.15.4.gemfile
          - Gemfile
        exclude:
          - ruby: '3.0'
            gemfile: 'gemfiles/faraday-0.15.4.gemfile'
          - ruby: '3.1'
            gemfile: 'gemfiles/faraday-0.15.4.gemfile'

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          
      - name: Run tests
        run: bundle exec rake

  finish:
    runs-on: ubuntu-latest
    needs: [ test_matrix ]
    steps:
      - name: Wait for status checks
        run: echo "All Green!"
